### ISSUE TITLE
[FEAT] Tailwind notation

### ISSUE THREAD

**Issue by pbrochar** [prazzon/Flexbox-Labs#6]
Your tool is very usefull, thanks a lot for that.

It should be very interesting to have tailwind classes too in the `code` part.
What do you think ?

**Comment by prazzon** [comment]
Thanks for the feedback! Tailwind classes are one of the most requested features, so they'll be included in an upcoming update. Appreciate it!

**Comment by prazzon** [comment]
I’ve separated the components for displaying HTML and CSS into their own components, which sets the stage for a dedicated Tailwind display component.

Right now, I’m researching how to implement this and leaning towards using a third-party CSS-to-Tailwind converter since creating one from scratch isn’t within my current skillset. If anyone has ideas or suggestions on how to approach this—or would like to contribute—I’d love to collaborate!

**Comment by WhyFenceCode** [comment]
@prazzon in relation to what libraries to use, what is the framework in? i would assume you need some form of NPM package, and while i have never used it, i have seen this one used before: https://github.com/Jackardios/css-to-tailwindcss

**Comment by prazzon** [comment]
@WhyFenceCode I checked this out earlier and noticed some issues. Since I want more control over the process, I’ve decided to create a custom converter. It’ll focus specifically on flex item properties, so it won’t be a full CSS-to-Tailwind converter. I’m currently working on it and will push the update soon. Thanks!
